name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or the branch you want to build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: calavelas/vault-secret-checker:latest

